import Head from "next/head";
import Script from "next/script";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen  bg-gradient-to-b from-gray-900 to-slate-800 flex flex-col text-white">
    <h1>digi style www</h1>
      </div>
    </div>
  );
}
